### ISSUE TITLE
PRODUCTION ERROR

### ISSUE THREAD

**Issue by infokartasplit** [wavded/ogr2ogr#100]
on dev server everything works fine but on production i get this error:
`
Error: spawn ogr2ogr ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ogr2ogr',
  path: 'ogr2ogr',
  spawnargs: [
    '-f',
    'dxf',
    '-skipfailures',
    '/tmp/ogr_1682326233801.dxf',
    '/vsistdin/'
  ],
  cmd: 'ogr2ogr -f dxf -skipfailures /tmp/ogr_1682326233801.dxf /vsistdin/'
}

`

`ogr2ogr --version
GDAL 3.3.2, released 2021/09/01
`

**Comment by wavded** [comment]
This error happens when Node cannot find `ogr2ogr` command on your system (gdal package). If it is installed, make sure its available in the `PATH` so Node can find it.
