### ISSUE TITLE
/vsicurl/ can not be used with all kind of http or ftp resources

### ISSUE THREAD

**Issue by jgrocha** [wavded/ogr2ogr#102]
`/vsicurl/` prefix is being added to all resources matching `/^(http|ftp)/`

https://github.com/wavded/ogr2ogr/blob/729f321dd96414e256aa67be1bc76f0b0a9b21dc/index.ts#L105

There are several cases where `/vsicurl/` can not be used and `/vsicurl_streaming/` should be used instead. In my use case, I'm downloading WFS requests failing with `/vsicurl/`.

Users can add this prefix by themselves, if they want to. I don't think this should be added by the lib, behind the scenes. 

Any comments against removing this from the library? I would like to discuss it before any PR.

**Comment by wavded** [comment]
Would it make sense to use `/vsicurl_sreaming/` instead of `/vsicurl/` ? Reason being is the API is more accessible if we don't require a user to know to append that to their FTP and HTTP endpoints. Or perhaps we allow an override for advanced uses?
