### ISSUE TITLE
Convert files uploaded by user

### ISSUE THREAD

**Issue by XW-Liron** [wavded/ogr2ogr#103]
Hey, this is more of a question than an issue. I've been looking for a tool to convert shapefile zips to Geo JSON. This package caught my eye. I was curious to know if its possible to convert files you don't know the path of. For example, files that are uploaded via <input type="file"> (one cannot get full paths of files uploaded to browser for security reasons). Would appreciate any guidance you can give.

**Comment by wavded** [comment]
@XW-Liron sorry for the delayed response. You can pass a stream in so you wouldn't need a path if you have a streamable request body. Would that work?
