### ISSUE TITLE
ENOENT error on windows

### ISSUE THREAD

**Issue by DemarsM** [wavded/ogr2ogr#17]
I would like to know if this module is compatible with Windows?
I have GDAL 1.10 32bits installed on Windows 7.

Doing something like that:

    var shapefile = ogr2ogr('c:/temp/test.geojson')
                    .format('ESRI Shapefile')
                    .skipfailures()
                    .stream()
    shapefile.pipe(fs.createWriteStream('c:/temp/shapefile.zip'))

returns 

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: Error: spawn ogr2ogr ENOENT
        at ChildProcess.<anonymous> (c:\node\decoupage\node_modules\ogr2ogr\index.js
    :187:28)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)
        at Socket.<anonymous> (child_process.js:1183:11)
        at Socket.emit (events.js:107:17)
        at Pipe.close (net.js:485:12)
    Program node ./bin/www exited with code 1

**Comment by wavded** [comment]
It should be compatible, that error would indicate that Node cannot find the `ogr2ogr` executable in your PATH which is part of the gdal tools.

**Comment by DemarsM** [comment]
Ok, but ogr2ogr is in the PATH environment variable. I can use it directly in commdand prompt

**Comment by DemarsM** [comment]
Thank you!

You were correct, that was the problem.

**Comment by wavded** [comment]
Glad you got it working!
