### ISSUE TITLE
error with url geojson

### ISSUE THREAD

**Issue by DemarsM** [wavded/ogr2ogr#18]
Maybe I have this problem because my url is on localhost?

I have this geojson at the following url: http://localhost:3000/admin/711/lines.geojson

    {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"LineString","coordinates":[[-7576433,6176485],[-7307069,6261483]]},"properties":{"id":38,"codecs":"711","featureId":"025c4e24-6c1e-be63-fe48-27500a55b957","styleId":"Nouvelles limites","createdAt":"2015-09-16T15:09:50.409Z","updatedAt":"2015-09-16T15:09:50.768Z"}}],"crs":{"type":"link","properties":{"href":"http://spatialreference.org/ref/sr-org/6864/proj4/","type":"proj4"}}}

Im doing like this: 

    var tableExport = ogr2ogr('http://localhost:3000/admin/711/lines.geojson')
        .format('MapInfo File')
        .stream()
        tableExport.pipe(fs.createWriteStream(mapInfoPath));

I have the following error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ERROR 1: HTTP error code : 504
FAILURE:
Unable to open datasource `http://localhost:3000/admin/711/lines.geojson' with t
he following drivers...

**Comment by wavded** [comment]
@DemarsM could be a localhost issue, but what is interesting is you have a 504 bad gateway response, is there a proxy running locally?

**Comment by DemarsM** [comment]
Yes I am behind a proxy, but I have to tell you that using the url (https://gist.github.com/wavded/7376428/raw/971548233e441615a426794c766223488492ddb9/test.geojson) found in the geojson-url.js example is working. If ogr2ogr was not able to be used through my proxy, the geojson-url.js would fail the same no?

**Comment by DemarsM** [comment]
I am serving the geojson at http://localhost:3000/admin/711/lines.geojson like below (its not a static geojson file)

                res.writeHead(200, {'Content-Type': 'application/json'});
                res.end(JSON.stringify(geojson));

**Comment by wavded** [comment]
@DemarsM that shouldn't make a difference (dynamic vs static), seems like there is an issue in the proxy as the request made received a 504 from the proxy server.  Have you tried using `curl` or some other http client to test?

**Comment by DemarsM** [comment]
@wavded You are right, the problem is with the proxy. The url can be accessed by web browsers, but not by other clients. I have tested with another client  andI have the same 504 error than with ogr2ogr.

This issue is out of the scope for here. Thank you for your help!

**Comment by DemarsM** [comment]
@wavded The end of the story: the company where I work used to be behind a proxy, but the technicians remove it lately without telling us. The proxy and https-proxy variables that was set on my system, was causing the 504 error. Now that I removed it, everything is working fine.

Thank you again

**Comment by wavded** [comment]
@DemarsM glad you got it figured out!
