### ISSUE TITLE
GPX to geoJSON conversion

### ISSUE THREAD

**Issue by nicolas-bonnel** [wavded/ogr2ogr#19]
GPX can have multiple layers (tracks, routes, waypoints), but even when only one layer is defined, the conversion fails : 
```
"ERROR 6: GeoJSON driver doesn't support creating more than one layer",
"ERROR 1: Terminating translation prematurely after failed",
"translation of layer routes (use -skipfailures to skip errors)"
```

By specifying the layer on the command line, the conversion can be done by ogr2ogr. It would be great if we could add extra arguments to the ogr2ogr command line using the /convert api

**Comment by wavded** [comment]
`.options(arr)` doesn't work?

**Comment by nicolas-bonnel** [comment]
Oh Sorry I wanted to post the issue on the ogre project. Messed up with browser tabs. I think my problem is related to https://github.com/wavded/ogre/issues/33. You closed that issue but the posted example has only one layer (tracks) but still can't be converted because the layer name can't be passed as argument to the ogr2ogr command.

Can this issue be re-opened ?
