### ISSUE TITLE
Working example of reading from PostgreSQL table

### ISSUE THREAD

**Issue by vgeorge** [wavded/ogr2ogr#21]
Is it posible to read from a PostgreSQL table, as in the example below?

```
ogr2ogr -overwrite output_shape PG:"user=example_user dbname=example_db" <input_table>
```

I couldn't find a way after looking at the examples/test folders.

**Comment by kriscarle** [comment]
Maybe something like this?

```js

var shapefile = ogr2ogr('PG:"user=example_user dbname=example_db" "<input_table>"')
                    .format('ESRI Shapefile')
                    .stream()
shapefile.pipe(fs.createWriteStream('/output_shape'))

```

The other option would be to select the data out of PostGIS and convert to GeoJSON in node, then pass the GeoJSON object to ogr2ogr, something like http://gis.stackexchange.com/questions/35171/creating-proper-geojson-from-postgis-data-using-node-js

**Comment by wavded** [comment]
Closing due to age, reopen if issue persists.
