### ISSUE TITLE
Example Exporting Postgresql Query to Shapefile

### ISSUE THREAD

**Issue by 1Map** [wavded/ogr2ogr#23]
Hi,

Do you have an example where my source is **Postgresql** and destination is **Shp**.  Problem is my Source is not a postgresql table, but a postgresql SELECT query.  In ogr2ogr on the command line, I use to work with:

`-sql "SELECT field1, field2 FROM sometable"`

How would this be done in nodejs ogr2ogr as I cannot find any example of this?

**Comment by wavded** [comment]
Sure.  You can provide any options via the `.options()` call in your ogr2ogr chain.  So in this case you'd have something like:

```
.options(['-sql', 'SELECT field1, field2 FROM sometable'])
```

**Comment by 1Map** [comment]
@wavded Thanks for the help.  I managed to get it working.  One last question is:

I can export to any format, except DXF.  Have you got an example where I can export from Postgresql (Using SELECT query) to DXF?

**Comment by wavded** [comment]
Assuming you've tried `.format('DXF')`, you may want to check your local gdal installation and see if that format is supported in your installation `ogr2ogr --long-usage`.

**Comment by 1Map** [comment]
It is supported and if I manually run ogr2ogr from the command line to export to DXF, it works.

**Comment by 1Map** [comment]
I have also found a bug in the ogr2ogr nodejs app.

In: index.js

```
  function wrapUp(er) {
    if (er) {
      ostream.emit('error', er)
      return ogr2ogr._clean()
    }....
```

In the above code, the line: `return ogr2ogr._clean()` never get called it raise an error on `ostream.emit('error', er)` and stops, but never reach `ostream.emit('error', er)`

**Comment by 1Map** [comment]
I get following errors when trying to export to DXF:

ERROR 6: Read or update mode not supported on /vsistdout
ERROR 4: Failed to open '/vsistdout/' for writing.
ERROR 1: DXF driver failed to create /vsistdout/

**Comment by 1Map** [comment]
When I run from command line it works:

`
ogr2ogr -t_srs "EPSG:4326" -a_srs "EPSG:4326" -f "DXF" "/data/test/SXXO26.dxf" -skipfailures PG:"host=127.0.0.1 port=5432 user=myusername dbname=mydb password=mypassword" -sql "SELECT st_setsrid(st_transform("the_geom", 4326), 4326) AS feature FROM "myerven" WHERE draw_layer='E' AND st_setsrid(st_geomfromtext('POLYGON((19.00939836050491 -33.6532873735,19.012311239495084 -33.6532873735,19.012311239495084 -33.65497526864113,19.00939836050491 -33.65497526864113,19.00939836050491 -33.6532873735))'), 4326) && "the_geom" AND st_intersects(st_setsrid(st_geomfromtext('POLYGON((19.00939836050491 -33.6532873735,19.012311239495084 -33.6532873735,19.012311239495084 -33.65497526864113,19.00939836050491 -33.65497526864113,19.00939836050491 -33.6532873735))'), 4326), "the_geom")"
`

When running from code it does not work and gives errors as above:

```
                                        var shapefile = ogr2ogr('PG:host=127.0.0.1 port=5432 user=myusername dbname=mydb password=mypassword')
                                            .format('DXF')
                                            .options(['-sql', 'SELECT st_setsrid(st_transform("the_geom", 4326), 4326) AS feature FROM "myerven" WHERE draw_layer='E' AND st_setsrid(st_geomfromtext('POLYGON((19.00939836050491 -33.6532873735,19.012311239495084 -33.6532873735,19.012311239495084 -33.65497526864113,19.00939836050491 -33.65497526864113,19.00939836050491 -33.6532873735))'), 4326) && "the_geom" AND st_intersects(st_setsrid(st_geomfromtext('POLYGON((19.00939836050491 -33.6532873735,19.012311239495084 -33.6532873735,19.012311239495084 -33.65497526864113,19.00939836050491 -33.65497526864113,19.00939836050491 -33.6532873735))'), 4326), "the_geom")'])
                                            .project('EPSG:4326')
                                            .skipfailures()
                                            .stream();

```

**Comment by wavded** [comment]
It appears DXF doesn't support streaming.  Instead of `.stream()` you could try `.destination()` which forces ogr2ogr to output the file directly instead of streaming it back to Node.

**Comment by wavded** [comment]
E.g. `.destination('/path/to/output.dxf')`

**Comment by 1Map** [comment]
Let me try and I will come back to you.  Thanks again for the help.

**Comment by 1Map** [comment]
How would I add a callback on done / error if I use destination ?

**Comment by wavded** [comment]
Good question :). I think you can do this, but I haven't tested it.  At the end of your chain add a `.on('end', handlerFunc)` where you do something when `handlerFunc` is called.

**Comment by 1Map** [comment]
Or maybe inside:

```
.exec(function(er, data) {
  if (er) console.error(er)
  // Done -> Continue
})
```

**Comment by 1Map** [comment]
@wavded All seems 100% now, except for one last thing:

When I export to let's say Shapefile, then it creates a zip file with the 4 files:
sql_statement.shp
sql_statement.shx
sql_statement.prj
sql_statement.dbf

Question: How can I prevent it from giving it the filename: sql_statement?  I want to give the filenames my own custom name.

**Comment by 1Map** [comment]
No Problem.  I managed to get it working by passing all exports through destination and then handling my own zip.  Closing this for now.
