### ISSUE TITLE
Do not remove target projection when loading from csv

### ISSUE THREAD

**Issue by 1Map** [wavded/ogr2ogr#24]
Even if no vrt is generated from a csv, do not delete the target SRS as this is giving errors in generating the target:

FAILURE: if -s_srs is specified, -t_srs must also be specified

This line should not be there (in index.js):

`delete ogr2ogr._targetSrs`

```
    else if (ogr2ogr._isCsvIn) {
      csv.makeVrt(fpath, function(err, vrt) {
        if (vrt && /\.vrt$/.test(vrt)) {
          // always set a source srs
          if (!ogr2ogr._sourceSrs) ogr2ogr._sourceSrs = ogr2ogr._targetSrs
        } else {
          // no geo data so no target srs
          delete ogr2ogr._targetSrs
        }
        one(err, vrt)
      })
    }
```

Error: 
FAILURE: if -s_srs is specified, -t_srs must also be specified

    at ChildProcess.<anonymous> (/home/ouser/onemapnginx/node_modules/ogr2ogr/index.js:187:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by wavded** [comment]
I honestly forget why that line exists.  Do you have success if you remove it?

**Comment by 1Map** [comment]
Yes, I do

**Comment by 1Map** [comment]
This error is only there if my Source is a CSV file.  Of course, that is the only time `makeVrt` is called and in turn delete `ogr2ogr._targetSrs`

Another question.  Is there an optional parameter "NOT" to generate Vrt as I handle this myself.

**Comment by wavded** [comment]
If you pass a VRT zipped up with any other file (that the VRT references like a CSV), you can provided your own in that case.

**Comment by wavded** [comment]
Closing due to age, reopen if issue persists.
