### ISSUE TITLE
GeoJSON Object Errors

### ISSUE THREAD

**Issue by danielrasmuson** [wavded/ogr2ogr#25]
With version 6.9.4 of node when I run from within `examples`...

```
node geojson-obj.js
```

**Contents of geojson-obj.js**
```
var ogr2ogr = require('../')

var geojson = {
  'type': 'FeatureCollection',
  'features': [{
    'type': 'Feature',
    'geometry': {
      'type': 'Point',
      'coordinates': [102.0, 0.5],
    },
    'properties': {'area': '51'},
  }],
}

var ogr = ogr2ogr(geojson).project('EPSG:3857')

ogr.exec(function(er, data) {
  if (er) console.error(er)
  console.log(data) // reprojected geojson data
})
```

I get the following error

```
⋊> ~/D/G/n/o/examples node geojson-obj.js                                                                                                                                  11:54:25
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at PassThrough.<anonymous> (/Users/danielrasmuson/Downloads/GeoJSONtoDXF/node_modules/ogr2ogr/index.js:91:27)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at wrapUp (/Users/danielrasmuson/Downloads/GeoJSONtoDXF/node_modules/ogr2ogr/index.js:207:15)
    at /Users/danielrasmuson/Downloads/GeoJSONtoDXF/node_modules/ogr2ogr/lib/util.js:56:5
    at ChildProcess.<anonymous> (/Users/danielrasmuson/Downloads/GeoJSONtoDXF/node_modules/ogr2ogr/index.js:187:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
undefined
```

**Comment by wavded** [comment]
@danielrasmuson I'm unable to duplicate using latest Node v6 or v7.  I get the following response:

```
{ type: 'FeatureCollection',
  crs:
   { type: 'name',
     properties: { name: 'urn:ogc:def:crs:EPSG::3857' } },
  features: [ { type: 'Feature', properties: [Object], geometry: [Object] } ] }
```

What version of ogr2ogr are you running? `ogr2ogr --version`

**Comment by Peter-Gabel** [comment]
I had the very same problem.  It appears that the generation of the GeoJSON FeatureCollection does NOT buffer the way you might expect. I was expecting that I could grab each feature by stripping off the beginning lines (denoting the FC) and get line-by-line features with a trailing comma.  Most of the time that works but occasionally a line does not contain a complete feature for conversion to an object.

As a test, I have been converting Census.gov Zip code geometry files (ZCTA5 500K). These are large enough that every 2 or three attempts the error occurs.

My solution was to stream the output of ogr2ogr to a file.  Then I read in the file line-by-line, stripping off the beginning and commas at the end of lines (except for the last feature).  It's inelegant that I need to write and then read a file, but it seems to be a reliable solution.

ogr2ogr --version
GDAL 1.11.4, released 2016/01/25

I'd love to hear of a better solution.

**Comment by broncha** [comment]
I am getting this now. But it's not consistent. Sometimes it just works, and sometimes it throws this exception.

**Comment by wavded** [comment]
Closing due to age, reopen if issue persists.

**Comment by Peter-Gabel** [comment]
great strategy.  If an issue is old enough, just close it out.

 

-p

 

 

Peter L. Gabel | President | Headspace Sprockets, LLC. | 508-272-9947

 <http://www.headspacesprockets.com/> www.headspacesprockets.com |  <http://www.petergabel.info> petergabel.info

 

“Explanations exist; they have existed for all time; there is always a well-known solution to every human problem—neat, plausible, and wrong.” 
―  <https://www.goodreads.com/author/show/7805.H_L_Mencken> H.L. Mencken

**Comment by wavded** [comment]
Is this still an issue for you @Peter-Gabel? Feel free to reopen if so. Providing sample code that fails would help for me to address it. And if you have an insight into a fix from your testing, a PR would also be welcome.

As the sole maintainer of this project, closing old, possibly irrelevant, issues helps me keep my task list organized but I want to leave the option open for the asker to reopen if it indeed is still relevant and should be attended to.  Other maintainers automate this with bots, which I may consider in the future so it's not personal. Feel free to let me know if you have other ideas.

**Comment by Peter-Gabel** [comment]
Marc,

Thanks for getting back to me.  I appreciate the work that you have been doing and that it is hard to be a sole maintainer of a project.  I really meant no disrespect and I apologize for my curt response.

I will check to see if there is still a problem.  This is code that I run infrequently.  It may be fine at this point. If not, I will reopen the issue.

Best regards,

Peter

 

 

Peter L. Gabel | President | Headspace Sprockets, LLC. | 508-272-9947

 <http://www.headspacesprockets.com/> www.headspacesprockets.com |  <http://www.petergabel.info> petergabel.info

 

“Explanations exist; they have existed for all time; there is always a well-known solution to every human problem—neat, plausible, and wrong.” 
―  <https://www.goodreads.com/author/show/7805.H_L_Mencken> H.L. Mencken
