### ISSUE TITLE
The program does not function properly

### ISSUE THREAD

**Issue by yippee2015** [wavded/ogr2ogr#26]
C:\Users\hhx\AppData\Roaming\npm\node_modules\ogr2ogr\examples>node geojson-obj.js

Error: Error: spawn ogr2ogr ENOENT
    at ChildProcess.<anonymous> (C:\Users\hhx\AppData\Roaming\npm\node_modules\ogr2ogr\index.js:187:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
undefined

**Comment by wavded** [comment]
This means that you don't have gdal installed on your system or the ogr2ogr tool is not accessible in your PATH.  See https://github.com/wavded/ogr2ogr#requirements

**Comment by yippee2015** [comment]
Yes，you are right. I didn't install gdal.
After installing gdal, how to configure paths of ogr2ogr tool?
Thanks for your help！ I'm looking forward to your reply.

**Comment by casperfibaek** [comment]
For windows, check step three of this tutorial: https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows

**Comment by yippee2015** [comment]
Hi @wavded  @casperfibaek Thanks a lot. It helped. 
I install OGRE project, ogr2ogr can work 
But when I  use the example node geojson-obj.js , I get
spawn ogr2ogr ENOENT Error. when i try to convert a file
I don't know what's wrong In the process，hopes your help

**Comment by wavded** [comment]
Closing due to age, reopen if issue persists.

**Comment by zachsa** [comment]
I get the same error. If I fork the code, and follow the instructions at https://stackoverflow.com/a/27883443/3114742, Then the output is this:

```
[Arguments] {
  '0': '/usr/bin/docker run --rm osgeo/gdal:alpine-small-latest ogr2ogr',
  '1': [
    '-f',
    'GeoJSON',
    '/vsistdout/',
    '/tmp/catalogue-api/pJMXmL/HST_indicators_2007-2019.shp'
  ],
  '2': undefined
}
```

If I try using `cp.exec` instead of `cp.spawn`, I get the error `FAILURE: no target datasource provided`
