### ISSUE TITLE
Convert SHP to Postgis UTF8

### ISSUE THREAD

**Issue by 1Map** [wavded/ogr2ogr#38]
I have a shp file in iso-8859-1.  How to import to Postgresql (UTF-8) ?

The problem is that my users can upload any character encoding shp file.  So the utility should always convert to UTF-8, no matter what the shp encoding is.

**Comment by wavded** [comment]
you can pass in any arbitrary options to `ogr2ogr`, is there not an option that will do that?

**Comment by wavded** [comment]
Closing due to age, reopen if issue persists.
