### ISSUE TITLE
ogr2ogr Warning: organizePolygons()

### ISSUE THREAD

**Issue by Mykolla** [wavded/ogr2ogr#43]
Hey!

Does anyone has idea how to deal with this error:

> **Warning 1:** organizePolygons() recieved an unexpected geometry. Either a polygon with interior rings or a polygon with less than 4 points or a non-Polygon geometry. Retrun arguments as collection.

What does it mean 'retrun arguments as collection?
I am using data in osm format. Error occurs for some polygons while using:

```
temp_path = path_to_folder
element = name_of_file
path = path_for_element

r'ogr2ogr {0} {1}.osm multipolygons -nln {2}_ply -lco ENCODING=UTF-8'.format(
        temp_path, os.path.join(path, element), element)
```

**Comment by wavded** [comment]
Closing due to age, reopen if issue persists.
