### ISSUE TITLE
KMZ not marked as a zip output

### ISSUE THREAD

**Issue by contra** [wavded/ogr2ogr#50]
Behavior here not getting trigger because the driver for KMZ does not have the right output attribute on it: https://github.com/wavded/ogr2ogr/blob/master/index.js#L158

https://github.com/wavded/ogr2ogr/blob/master/modules/drivers.json#L51

**Comment by contra** [comment]
Please keep this open.

**Comment by wavded** [comment]
@contra would you be interested in open a PR to address this?

**Comment by contra** [comment]
I did open one https://github.com/wavded/ogr2ogr/pull/51 just don't have time to dig into it further, I ended up having to write my own library for doing this via streams anyways https://www.npmjs.com/package/verrazzano
