### ISSUE TITLE
Extension: Support remote shapefile sources

### ISSUE THREAD

**Issue by efreethy** [wavded/ogr2ogr#62]
Great work on this library.

I am collecting large shape files from a remote ftp source server - persisting to disk on a path - then invoking ogr2ogr with the path. It would be awesome if I could just give this library 1. a remote FTP path and 2. a set of credentials, and  leave that extra legwork to the library.

**Comment by wavded** [comment]
This would be out of scope for this library but could wrap this module around some scripting to do this.
