### ISSUE TITLE
Ogr2ogr module doesn't give any output when doing promise?

### ISSUE THREAD

**Issue by ferily7** [wavded/ogr2ogr#66]
I'm tryin to use the module in a lambda function but I'm having some issues with it. The way I am using the ogr2ogr module is by doing `.promise()`. However when I try to run my lambda function, I don't see anything in the logs. It seems like it just never hits the promise? Here is how my code looks like with the promise:

```
let data = await ogr2ogr(path)
	.destination(database)
	.options(['-f "PostgreSQL"', '-nlt PROMOTE_TO_MULTI', 'nln <schemaName>."' + tableName + '"', '-overwrite']).promise();
console.log(data);
```

I'm doing it exactly the way the documentation says but it still doesn't work. Something I should point out is that I tried to do

let ogr = ogr2ogr(path)
	.destination(database)
	.options(['-f "PostgreSQL"', '-nlt PROMOTE_TO_MULTI', 'nln <schemaName>."' + tableName + '"', '-overwrite']);
console.log(ogr);

And I do see  something in the logs:

```
EventEmitter {
      _inPath: '<path_of_file>',
      _onStderr: [Function (anonymous)],
      _driver: {},
      _args: [],
      _timeout: 15000,
      _format: 'GeoJSON',
      _skipfailures: false,
      _testClean: [Function (anonymous)],
      _destination: PG:host=<hostendpoint> user=<username> dbname=<db> password=<password>,
      _options: [
        '-f "PostgreSQL"',
        '-nlt PROMOTE_TO_MULTI',
        'nln schemaName.tableName',
        '-overwrite'
      ]
}

```
But if I try to do a callback like the documentation says, using the `.exec()` function, I don't see anything outputted. Is there an example that I can reference that uses a promise? Any help is greatly appreciated!

**Comment by wavded** [comment]
If you specify a `destination` there won't be much if any output as its being sent to another destination other than stdout.

**Comment by ferily7** [comment]
Oh hmm I see so there won't be anything outputted in the logs then if doing a destination? I don't see my file after the function is done though

**Comment by wavded** [comment]
I have not used PostgreSQL as a destination before so not sure what what the gdal `ogr2ogr` tool would output in that case.  Have you tried running this directly on the command line to see the output?  You should get everything sent to stdout that command would sent you, everything sent to stderr would be send to `onStderr` if you have that hook set up.

**Comment by ferily7** [comment]
I tried to test this locally on my computer and not on the lambda function but I get `Error: Error: spawn ogr2ogr ENOENT`

I'm assuming it has to do with GDAL? I installed GDAL through OSGeo4W though, is there any other further steps I need to do?

**Comment by ferily7** [comment]
Actually I managed to get it to work locally -- I had GDAL installed but I needed to add it as a PATH in my environmental variable, so I am able to get ogr2ogr to send my file to PostgreSQL as the destination.

As for on the lambda, I got that to work by doing `await` and `promise()`
