### ISSUE TITLE
CSV support?

### ISSUE THREAD

**Issue by ferily7** [wavded/ogr2ogr#67]
I'm trying to send a csv file over to my postgres  but I noticed that I get the following error:

```
Unable to open datasource `fileName.csv' with the following drivers.
  -> `netCDF'
  -> `PDS4'
  -> `VICAR'
  -> `JP2OpenJPEG'
  -> `MBTiles'
  -> `BAG'
  -> `ESRI Shapefile'
  -> `MapInfo File'
  -> `OGR_VRT'
  -> `Memory'
  -> `GML'
  -> `KML'
  -> `GeoJSON'
  -> `GeoJSONSeq'
  -> `ESRIJSON'
  -> `TopoJSON'
  -> `GPKG'
  -> `SQLite'
  -> `PostgreSQL'
  -> `FlatGeobuf'
  -> `PGDUMP'
  -> `OGR_PDS'
  -> `MVT'
```

Is there no support for csv files?

**Comment by wavded** [comment]
CSV is supported through OGR_VRT, do you have a sample code snippet on how you are using this in code?

**Comment by ferily7** [comment]
Yes, my code looks like this:

```
let ogr = await ogr2ogr(path)
	.format('PostgreSQL')
	.destination(databaseHost)
	.options(['-nlt', 'PROMOTE_TO_MULTI', '-nln', 'schema.tableName, '-a_srs', 'EPSG:4326', '-oo', 'X_POSSIBLE_NAMES="' + long + '"', '-oo', 'Y_POSSIBLE_NAMES="' + lat + '"', '-overwrite',]).promise();
```

where `path` is the path to the CSV file and `databaseHost` is my database credentials

**Comment by wavded** [comment]
specifying a destination can sometimes cause issues but, out of curiosity, does this work:

```
let ogr = await ogr2ogr(fs.createReadStream(path), 'csv')
	.format('PostgreSQL')
	.destination(databaseHost)
	.options(['-nlt', 'PROMOTE_TO_MULTI', '-nln', 'schema.tableName, '-a_srs', 'EPSG:4326', '-oo', 'X_POSSIBLE_NAMES="' + long + '"', '-oo', 'Y_POSSIBLE_NAMES="' + lat + '"', '-overwrite',]).promise();
```

**Comment by ferily7** [comment]
Hmmm still didn't work for me

**Comment by ferily7** [comment]
Actually I just noticed that the error is the same, but the csv file it's trying to read isn't the csv file that I'm trying to read?

```
Unable to open datasource `/tmp/ogr_58238cb1275.csv' with the following drivers.
  -> `netCDF'
  -> `PDS4'
  -> `VICAR'
  -> `JP2OpenJPEG'
  -> `MBTiles'
  -> `BAG'
  -> `ESRI Shapefile'
  -> `MapInfo File'
  -> `OGR_VRT'
  -> `Memory'
  -> `GML'
  -> `KML'
  -> `GeoJSON'
  -> `GeoJSONSeq'
  -> `ESRIJSON'
  -> `TopoJSON'
  -> `GPKG'
  -> `SQLite'
  -> `PostgreSQL'
  -> `FlatGeobuf'
  -> `PGDUMP'
  -> `OGR_PDS'
  -> `MVT'
```

**Comment by ferily7** [comment]
So @wavded  I tried a different file and it seems like the module is successful but it didn't send over the data correctly to my destination... When I look at the table in my postgres, it's empty. Is there something wrong with csv and the destination?

**Comment by wavded** [comment]
Gosh, I don't have a great way to test this as I don't have a Postgres environment readily available.  Usually I try to mimic the command using the ogr2ogr command line tool itself to see.  I don't see anything API wise that is amiss with what you've shared.

**Comment by ferily7** [comment]
It seems to run the ogr2ogr command successfully but it isn’t writing the data in the csv correctly.. Hmm if I created a mock postgres database for you to test, will that work?

**Comment by ferily7** [comment]
The name of the table in my postgres is correct, but when I try to view all the data for that table, all I see is a `ogc_fid` column with nothing in it

**Comment by ferily7** [comment]
I also noticed that the same file writes to my postgres locally but when I try to do it on my lambda function, it doesn't work properly. The data isn't in the table
