### ISSUE TITLE
How to write -update statement ?

### ISSUE THREAD

**Issue by mohammedX6** [wavded/ogr2ogr#81]
i want to update my geoPackage using this command
 `ogr2ogr -skipfailures -update floridaData.gpkg "https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/COVID19Surge_Florida_InterventionScenarios/FeatureServer/1/query?where=OBJECTID+%3C1000&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&outSR=4362&returnGeometry=true&sqlFormat=standard&f=json&maxRecordCountFactor=30&outFields=*&returnExceededLimitFeatures=false&resultType=tile" -nln 1
`
How i can write it ?

**Comment by wavded** [comment]
It would be something like this:

```js
ogr2ogr("floridaData.gpkg", {
  options: ["-update", "-nln", "1"],
  destination: "https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/COVID19Surge_Florida_InterventionScenarios/FeatureServer/1/query?where=OBJECTID+%3C1000&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&outSR=4362&returnGeometry=true&sqlFormat=standard&f=json&maxRecordCountFactor=30&outFields=*&returnExceededLimitFeatures=false&resultType=tile"
})
```
