### ISSUE TITLE
how to use on angular project?

### ISSUE THREAD

**Issue by clavijojuan** [wavded/ogr2ogr#82]
Im trying to implements this api on angular project but i had been some problems with this. Im new with this so i want to make some questions.

¿Can i use this api on frontend aplication?
¿have i install GDAL tools locally?
¿is posible to use a GDAL web package instead locally GDAL tools?

Thanks

**Comment by wavded** [comment]
This requires a server or container with `gdal` installed on it so it will not work on frontend applications.

**Comment by clavijojuan** [comment]
Thanks
