### ISSUE TITLE
OGR_XLSX_HEADERS

### ISSUE THREAD

**Issue by 1Map** [wavded/ogr2ogr#83]
How do I pass the Configuration Option "OGR_XLSX_HEADERS = FORCE" for XLSX files?

https://gdal.org/drivers/vector/xlsx.html

**Comment by wavded** [comment]
Use the input or output option -> https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-oo

The readme shows an example:

https://github.com/wavded/ogr2ogr#tips-and-tricks
