### ISSUE TITLE
change http method

### ISSUE THREAD

**Issue by mohammedX6** [wavded/ogr2ogr#88]
I am trying to call an ESRI feature service with a long URL using the ESRIJSON driver, an error appeared from the GIS server

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""[http://www.w3.org/TR/html4/strict.dtd">](http://www.w3.org/TR/html4/strict.dtd%22%3E)
<HTML><HEAD><TITLE>Request URL Too Long</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Request URL Too Long</h2>
<hr><p>HTTP Error 414. The request URL is too long.</p>
</BODY></HTML>
```
I find out that I must change my request from GET to POST
`vsicurl` supports POST
from ogr2ogr How do I change my request from GET to POST ?

**Comment by wavded** [comment]
Hey @mohammedX6 , I don't see support for `POST` in vsicurl, unless I'm missing something here or you have a different reference?

https://gdal.org/user/virtual_file_systems.html#vsicurl

If you have access to the GIS server, you may be able to bump up the request URL limit as well.
