### ISSUE TITLE
How to export postegresql table to .shp using org2org?

### ISSUE THREAD

**Issue by DanielleRS** [wavded/ogr2ogr#92]
Hi,

I'm trying to export a postgresql database view to shapefile using org2org but I'm not succeeding.

I did the following:

`const ogr2ogr = require('ogr2ogr').default;
var shapefile = ogr2ogr('PG:dbname=postgres host=localhost port=5432 user=postgres password=xxx', 
                    {
                        format: 'ESRI Shapefile', 
                        options: ['-sql', 'SELECT * FROM ViewTest'], 
                        project: 'ESPG:4326',
                        destination: 'C:\\Users\\Danielle\\output.shp'
                    });

 console.log(shapefile);`

Can you help me?

**Comment by wavded** [comment]
It looks like you aren't awaiting the promise. You probably want to catch any errors as well.

```js
const ogr2ogr = require('ogr2ogr').default;

(async() {
  try {
    let shapefile = await ogr2ogr(
      'PG:dbname=postgres host=localhost port=5432 user=postgres password=xxx', {
        format: 'ESRI Shapefile',
        options: ['-sql', 'SELECT * FROM ViewTest'],
        project: 'ESPG:4326',
        destination: 'C:\Users\Danielle\output.shp'
    });
    console.log("shapefile", shapefile);
  } catch (err) {
    console.error("error", err);
  }
})()
```

See https://github.com/wavded/ogr2ogr#usage for more examples.
